### ISSUE TITLE
Req 11.4: If you are the creator of the project, you should be able to see the awards even if it's draft or cancelled

### ISSUE THREAD

**Issue by guillermo-ag-95** [VictoriaCalbet/D12-Grupo-7#16]
If you click in "Show awards" of an own draft or cancelled project, we get a HTTP 500

**Comment by kain90** [comment]
You are right. Here is the solution: 

Services: https://github.com/VictoriaCalbet/D12-Grupo-7/commit/c4f62dd46a483991bf58cf0e1af0220cdc5abef0

Controllers: https://github.com/VictoriaCalbet/D12-Grupo-7/commit/ec2b235f0ebd48d75982d751041c1c46c8452ac0

**Comment by guillermo-ag-95** [comment]
Done!
