### ISSUE TITLE
Req 11.4: You can create awards to due projects

### ISSUE THREAD

**Issue by guillermo-ag-95** [VictoriaCalbet/D12-Grupo-7#17]

**Comment by kain90** [comment]
You're right. Here is the solution: 

**Controllers**: https://github.com/VictoriaCalbet/D12-Grupo-7/commit/1debb9f92a77abc6e7159f4729b8b6c7eb73ccd5
https://github.com/VictoriaCalbet/D12-Grupo-7/commit/6585114fe9ea944ad1323b76ac4d1e97f6beb4cc
**Services**: https://github.com/VictoriaCalbet/D12-Grupo-7/commit/ef9c4593e8cf1d7e42795d07ea2294d2977a3a67

**Comment by guillermo-ag-95** [comment]
Done!
