### ISSUE TITLE
Req 11.5: patronage/user/listPatronagesToMyProjects.do does not show any project

### ISSUE THREAD

**Issue by guillermo-ag-95** [VictoriaCalbet/D12-Grupo-7#30]

**Comment by davidromesp** [comment]
![image](https://user-images.githubusercontent.com/32366797/40556739-18712c5c-604e-11e8-8985-3db18cb8deae.png)

**Comment by guillermo-ag-95** [comment]
Wrong interpretation. My fault. Name was changed in header and now, it makes more sense.
