### ISSUE TITLE
Req 11.5: You can access to the patronage form via URL if you are its creator

### ISSUE THREAD

**Issue by guillermo-ag-95** [VictoriaCalbet/D12-Grupo-7#8]
Copy the link used to access to the form with one user and log in as creator. Copy the link and you will access the form.

**Comment by davidromesp** [comment]
f40035d4dda804d5292dc8c8e982e6776990db05

Now, if you try to access to the form, appears a panic page, saying that there is an Assert.isTrue that is not true. The Assert is localized in PatronageFormService
When we redirect panics to welcome, it won't appear

**Comment by guillermo-ag-95** [comment]
Done
